build:
    environment:
        php: 
            version: '7.1'

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true