build:
    environment:
        php: 
            version: '7.1'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS test_db"

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true