build:
    environment:
        php: 
            version: '7.4'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS test_db"

before_commands:
    - "composer install --prefer-source"

tools:
    php_code_coverage:
        test_command: vendor/bin/phpunit

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*
