language: php

php:
  - '7.0'
  - '7.1'
  
before_script:
  - composer self-update

install:
  - composer install

#script:
#  - vendor/bin/phpunit --filter run_only_when_local

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml