language: php

php:
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
  - composer self-update
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `test_db`;'

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml